spring:
  redis:
    host:localhost
    port:6379
  datasource:
    url: jdbc:mariadb://localhost:3306/demo_project
    username: root
    password: sample
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zome: Asia/Seoul
  security:
    jwt:
      secret: 9976ed8529fe16bb7b86662aa6f2ef6f1048120d7bebbd723b66f0e0ef1d4cac04d6ae2d1b3f849c0a7db271d40215db2648c9c70e71b337308ee3ab867b3492
      expiration: 60000 # 1분 테스트
      refreshTokenExpiration: 864000000 # 10 day in milliseconds
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher